# Problem 1. American Handwriting

In [ ]:
# import pandas as pd
# import numpy as np
# from keras.datasets import mnist

# (train_X, train_y), (test_X, test_y) = mnist.load_data()

Don't run the mnist until you are ready. You get x amount of resources for google collab per month apparently.

# Part 1: Derivative

*f*(x)$_i$ = $\frac{e_i^x}{\sum_je_j^x}$ 

gradient = $\begin{cases} f(x)_i(1-f(x)_i) & j = i\\-f(x)_if(x)_j & j\ne i \end{cases}$

In [2]:
import math
import numpy as np
# help from: https://slowbreathing.github.io/articles/2019-05/softmax-and-its-gradient
def softmax(vector):
  ''' Takes a vector (np.array) and returns softmax matrix '''
  result = []
  for row in vector:
    vals = np.asarray(row)
    result.append(np.exp(vals)/float(sum(np.exp(vals))))

  return np.array(result)

def softmax_gradient(vector):
  ''' 
  Takes a softmax vector (np.array) and returns the softmax gradient matrix 
  '''
  matrix = np.diag(vector)
  for i in range(len(matrix)):
    for j in range(len(matrix)):
      if i == j:
        matrix[i][i] = vector[i] * (1-vector[i])
      else:
        matrix[i][j] = -vector[i]*vector[j]
  return matrix

In [6]:
# Test run of softmax and gradient
x = np.array([[1,3,5,7]])
sm = softmax(x)
print(sm[0])
sm_grad = softmax_gradient(sm[0])
print()
print(sm_grad)

[0.00214401 0.0158422  0.11705891 0.86495488]

[[ 2.13941201e-03 -3.39658185e-05 -2.50975338e-04 -1.85447085e-03]
 [-3.39658185e-05  1.55912258e-02 -1.85447085e-03 -1.37027892e-02]
 [-2.50975338e-04 -1.85447085e-03  1.03356124e-01 -1.01250678e-01]
 [-1.85447085e-03 -1.37027892e-02 -1.01250678e-01  1.16807938e-01]]


# Part 2: Simple


%%time gives the current time, use to determine which is faster
Python Engineer on YouTube has good from scratch vids

make sure keras input layer dimension should correspond with your scratch program

follow up on learning rate for keras in 3. keep it simple

In later hidden layers, could be smaller, eventually getting into the 10 node output layer

In [ ]:
# help from: https://towardsdatascience.com/math-neural-network-from-scratch-in-python-d6da9f29ce65

class NeuralNet:
  def __init__(self):
    self.layers = []
  
  def add(self, layer):
    self.layers.append(layer)

  def fit(self, x_train, y_train, iterations, learn_rate):